# Generated by Django 4.2.23 on 2025-07-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('bias', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('summary', models.TextField()),
                ('ai_rewrite', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='articles/')),
                ('sources', models.ManyToManyField(to='core.source')),
            ],
        ),
    ]
